### ISSUE TITLE
Generate documentation to be store in gh pages

### ISSUE THREAD

**Issue by toloco** [toloco/pyoanda#23]
Generate with travis the sphinx documentation to be stored in github pages

**Comment by toloco** [comment]
Use this as template https://github.com/teracyhq/sphinx-deployment/tree/develop

**Comment by toloco** [comment]
read the docs might be a much better option

http://pyoanda.readthedocs.org/

**Comment by elyobo** [comment]
Yeah, readthedocs was my idea and how I tested my branch - see https://pyoand-elyobo-fork.readthedocs.org/en/sphinx-support/ for how it looked then.

**Comment by toloco** [comment]
I paired with the markdown readme, so I may say it's ok for know.

Might be need some improvements for version 1.0 ;)
