### ISSUE TITLE
Order.check() price validation

### ISSUE THREAD

**Issue by elyobo** [toloco/pyoanda#8]
Order.check() currently verifies that the price is an integer or float; however floats suffer from inaccuracies due to floating point arithmetic.  Generally I'm using decimal/cdecimal for safer calculations and it seems like allowing more values that look like numbers as well, e.g. by permitting anything that can be cast to a float or some other similar check.

**Comment by toloco** [comment]
You are right on this point...

I'll fix it ASAP

**Comment by toloco** [comment]
Please check this pull request
https://github.com/toloco/pyoanda/pull/9

**Comment by elyobo** [comment]
On the same note, we need to provide a way to set the options for the json parsing in Client.__call, for exactly the same reason.  By default JSON floats will get parsed to python floats, which introduces the same precision errors.  When using the streaming API to get prices I pass parse_float=decimal.Decimal to the json.loads() call that I use, which causes the parsing to automatically load the value into a Decimal object and avoiding the inaccuracy.

Perhaps a dict of args to use to load json as a property of the client, so that users can modify this behaviour if they need to?

**Comment by toloco** [comment]
Let me see your pull request

Honestly I prefer to add the parser inside the Client.__call instead of adding custom parser.

**Comment by elyobo** [comment]
Added a PR in #11.  We could pass the options in to __call() as well, but that would require changing the signature of all methods to include those option arguments and then for users of the client to set that option for every call.  For the purpose of controlling float parsing, it's definitely something that you'd want to set globally.

**Comment by toloco** [comment]
I like your solution, just a quick one
init(... json_option=None)
self.json_options = json_options or {}
Never use mutable objects as default arguments
http://docs.python-guide.org/en/latest/writing/gotchas/

**Comment by elyobo** [comment]
Ha, excellent, thanks for that.  I am new to python and that's a very handy gotcha.  I'll update the PR.

**Comment by toloco** [comment]
Pending to generate new pypi version (0.7)
